ERROR - 2022-12-27 00:18:36 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'thoriq'@'localhost' (using password: YES) in C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'thoriq', '12345', 'toko_online1', 3306, '', 0)
#1 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `barang`...', Array, false)
#4 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\toko1\app\Controllers\Shop.php(25): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(925): App\Controllers\Shop->index()
#8 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Shop))
#9 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\toko1\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `barang`...', Array, false)
#3 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\toko1\app\Controllers\Shop.php(25): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(925): App\Controllers\Shop->index()
#7 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Shop))
#8 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\toko1\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-12-27 00:18:36 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `barang`.*, `kategori`.`nama` AS `kategori`
FROM `barang`
JOIN `kategori` ON `barang`.`id_kategori`=`kategori`.`id`', [], false)
 3 SYSTEMPATH\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Shop.php(25): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\Shop->index()
 7 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Shop))
 8 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-27 00:18:53 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'thoriq'@'localhost' (using password: YES) in C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'thoriq', '12345', 'toko_online1', 3306, '', 0)
#1 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\toko1\app\Controllers\Auth.php(66): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(925): App\Controllers\Auth->login()
#8 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\toko1\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\BaseModel.php(624): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\toko1\app\Controllers\Auth.php(66): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(925): App\Controllers\Auth->login()
#7 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\toko1\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-12-27 00:18:53 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(66): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\Auth->login()
 7 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-27 00:19:05 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'thoriq'@'localhost' (using password: YES) in C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'thoriq', '12345', 'toko_online1', 3306, '', 0)
#1 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\toko1\app\Controllers\Auth.php(66): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(925): App\Controllers\Auth->login()
#8 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\toko1\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\BaseModel.php(624): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\toko1\app\Controllers\Auth.php(66): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(925): App\Controllers\Auth->login()
#7 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\toko1\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-12-27 00:19:05 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(66): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\Auth->login()
 7 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-27 00:19:27 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'thoriq'@'localhost' (using password: YES) in C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'thoriq', '12345', 'toko_online1', 3306, '', 0)
#1 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\toko1\app\Controllers\Auth.php(66): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(925): App\Controllers\Auth->login()
#8 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\toko1\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\BaseModel.php(624): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\toko1\app\Controllers\Auth.php(66): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(925): App\Controllers\Auth->login()
#7 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\toko1\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-12-27 00:19:27 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(66): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\Auth->login()
 7 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-27 00:19:52 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'thoriq'@'localhost' (using password: YES) in C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'thoriq', '12345', 'toko_online1', 3306, '', 0)
#1 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\toko1\app\Controllers\Auth.php(66): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(925): App\Controllers\Auth->login()
#8 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\toko1\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\BaseModel.php(624): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\toko1\app\Controllers\Auth.php(66): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(925): App\Controllers\Auth->login()
#7 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\toko1\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-12-27 00:19:52 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(66): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\Auth->login()
 7 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-27 00:21:26 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'thoriq'@'localhost' (using password: YES) in C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'thoriq', '12345', 'toko_online1', 3306, '', 0)
#1 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\toko1\app\Controllers\Auth.php(66): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(925): App\Controllers\Auth->login()
#8 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\toko1\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\BaseModel.php(624): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\toko1\app\Controllers\Auth.php(66): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(925): App\Controllers\Auth->login()
#7 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\toko1\vendor\codeigniter4\framework\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\toko1\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-12-27 00:21:26 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(66): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\Auth->login()
 7 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-27 00:22:40 --> 28 : Failed to connect to api.rajaongkir.com port 443: Timed out
in SYSTEMPATH\HTTP\CURLRequest.php on line 660.
 1 SYSTEMPATH\HTTP\CURLRequest.php(660): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('28', 'Failed to connect to api.rajaongkir.com port 443: Timed out')
 2 SYSTEMPATH\HTTP\CURLRequest.php(368): CodeIgniter\HTTP\CURLRequest->sendRequest([...])
 3 SYSTEMPATH\HTTP\CURLRequest.php(136): CodeIgniter\HTTP\CURLRequest->send('GET', 'https://api.rajaongkir.com/starter/province')
 4 APPPATH\Libraries\Bantuan.php(13): CodeIgniter\HTTP\CURLRequest->request('GET', 'https://api.rajaongkir.com/starter/province', [...])
 5 APPPATH\Controllers\Shop.php(54): App\Libraries\Bantuan->rajaongkir('https://api.rajaongkir.com/starter/province', 'eab7c40605109f565c0116b481679d0f', null, 'GET')
 6 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\Shop->product('2')
 7 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Shop))
 8 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-27 00:23:26 --> 35 : OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.rajaongkir.com:443 
in SYSTEMPATH\HTTP\CURLRequest.php on line 660.
 1 SYSTEMPATH\HTTP\CURLRequest.php(660): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('35', 'OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.rajaongkir.com:443 ')
 2 SYSTEMPATH\HTTP\CURLRequest.php(368): CodeIgniter\HTTP\CURLRequest->sendRequest([...])
 3 SYSTEMPATH\HTTP\CURLRequest.php(136): CodeIgniter\HTTP\CURLRequest->send('GET', 'https://api.rajaongkir.com/starter/province')
 4 APPPATH\Libraries\Bantuan.php(13): CodeIgniter\HTTP\CURLRequest->request('GET', 'https://api.rajaongkir.com/starter/province', [...])
 5 APPPATH\Controllers\Shop.php(54): App\Libraries\Bantuan->rajaongkir('https://api.rajaongkir.com/starter/province', 'eab7c40605109f565c0116b481679d0f', null, 'GET')
 6 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\Shop->product('2')
 7 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Shop))
 8 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
